### PR TITLE
Use future>=0.14.0 so 'html' is available in Python 2.7.

### PR DESCRIPTION
**Pull request by gbastien**
Hi,

new version fails to start on a fresh Plone because it misses the html requirement.

Could you please review and merge if OK?

By the way, could you have a look at the issue I posted months ago ;-)

Thank you!

Gauthier

### CODE REVIEW

**Comment by gbastien** [comment]
Hi,

yes I actually installed it using python 2.7 and Plone.

I do not know exactly how to manage compatibility issues between python 2.7 and python 3, moreover I do not understand how the Travis python2.7 build is green?

...

**Comment by gbastien** [comment]
Hi,
right this comes from the "future" package, we do not use a recent enough version, it seems it was included starting with future 0.14.0 (https://github.com/PythonCharmers/python-future/commit/4606bb2aa6b8156e9dd779824e328ed255591e0c) and we still use future 0.13.1 in Plone 4.3.14...

It is fine with Plone 5.x

You can ignore this, or maybe we ask for future >= 0.14.0 in setup.py?

Gauthier

**Comment by strichter** [comment]
I am in favor of requiring future >= 0.14.0. I can live with the patch as proposed as well, but it is not as nice.

**Comment by gbastien** [comment]
I updated the PR and now it is fine and working with Plone 4.3.x here so if it is ok with you, please merge.

Gauthier

**Comment by strichter** [comment]
Release 2.0.1 with this commit.

**Comment by gbastien** [comment]
Great thank you!

**Pull request merged**
